#!/bin/sh

mkdir -p opk
cp ./handy opk/handy
cp ./handy.png opk/handy.png

# Create GmenuNx entry file plus other things
cat > ./opk/default.gcw0.desktop <<EOF
[Desktop Entry]
Type=Application
Name=Handy
Comment=Atari Lynx emulator
Exec=handy %f
Icon=handy.png
Terminal=false
Type=Application
Categories=emulators;
EOF

mksquashfs ./opk handy_gcw0.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
